---
  environment: production
  chdir:  /home/oddthesis/git/cirras-management #/usr/share/cirras-management
  address: 0.0.0.0
  user: oddthesis # thin
  group: oddthesis # thin
  port: 4545
  pid: /var/lock/cirras-management.pid
  rackup: config.ru
  log: /var/log/cirras-management/thin.log
  max_conns: 100
  timeout: 30
  max_persistent_conns: 100
  daemonize: false # true
